name: Run linter, shellcheck, and unit tests on a branch
on: [ workflow_call, workflow_dispatch, pull_request ]
jobs:
  lint-and-test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ "1.21" ]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run linter
        run: "go vet ./..."
      - name: Run tests
        run: "go test ./..."
      - name: Run shellcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.6"
          install-go: false
          cache-key: ${{ matrix.go-version }}
