name: Release a Git Tag
on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: "Git tag"
        type: string
        required: true
jobs:
  lint-branch:
    uses: ./.github/workflows/lint-branch.yaml
    with:
      go-version: 1.21
  test-branch:
    uses: ./.github/workflows/test-branch.yaml
    with:
      go-version: 1.21
  release-tag:
    needs: [ lint-branch, test-branch ]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Create the git tag
        run: |
          git config --global user.name "Glove CI"
          git config --global user.email "glove-ci@users.noreply.github.com"
          git tag --annotate "${{ github.event.inputs.git_tag }}" --message "Version ${{ github.event.inputs.git_tag }}"
          git push origin "${{ github.event.inputs.git_tag }}"
